exporter_port: $EXPORTER_PORT|9090 # the port that exposes cost metrics
polling_interval_seconds: $POLLING_INTERVAL_SECONDS|28800 # by default it is 8 hours

group_by:
  enabled: true
  groups:
    - type: Dimension
      name: ServiceName
      label_name: ServiceName
  merge_minor_cost:
    # if this is enabled, minor cost that is below the threshold will be merged into one group
    enabled: false
    threshold: 10
    tag_value: other

target_azure_accounts:
  # here defines a list of target Azure accounts
  # it should be guaranteed that all the Azure accounts have the same set of keys (in this example they are Publisher, ProjectName, and EnvironmentName)
  - TenantId: PUT_YOUR_AZURE_TENANT_ID_HERE
    Subscription: PUT_YOUR_AZURE_SUBSCRIPTION_ID_HERE
    ProjectName: myproject
    EnvironmentName: dev